[package]
authors = ["James Tease <james@jamestease.co.uk>"]
name = "dungeon"
version = "0.1.0"

[dependencies]
arrayref = "0.3.4"
rand = "0.5"
sha2 = "0.7.1"

[dependencies.cairo-rs]
features = ["png"]
version = "0.3"
