[package]
authors = ["James Tease <james@jamestease.co.uk>"]
name = "dungeon"
version = "0.1.0"

[dependencies]
arrayref = "0.3.4"
clap = "2.32.0"
rand = "0.5"
serde = "1.0.68"
serde_derive = "1.0.68"
serde_json = "1.0.22"
sha2 = "0.7.1"

[dependencies.cairo-rs]
features = ["png"]
version = "0.3"
